development:
  AWS_ACCESS_KEY_ID: 'AKIAILE7AQ5SNDW4CVDA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
test:
  AWS_ACCESS_KEY_ID: 'AKIAILE7AQ5SNDW4CVDA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
production:
  AWS_ACCESS_KEY_ID: 'AKIAILE7AQ5SNDW4CVDA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
