development:
  AWS_ACCESS_KEY_ID: 'AKIAJZLOCUMACEB7J63A'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
test:
  AWS_ACCESS_KEY_ID: 'AKIAJZLOCUMACEB7J63A'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
production:
  AWS_ACCESS_KEY_ID: 'AKIAJZLOCUMACEB7J63A'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
