development:
  AWS_ACCESS_KEY_ID: 'AKIAIIN6TPBLFLJYN3MA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
test:
  AWS_ACCESS_KEY_ID: 'AKIAIIN6TPBLFLJYN3MA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
production:
  AWS_ACCESS_KEY_ID: 'AKIAIIN6TPBLFLJYN3MA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'groupbuy67'
